function createfigure1(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3)
%CREATEFIGURE1(X1, YMATRIX1, X2, YMATRIX2, X3, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 28-Feb-2016 19:21:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',3,'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 200]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Visible','off');
set(plot1(2),'LineWidth',3,'Color',[1 0 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2);
set(plot2(1),'Visible','off');
set(plot2(2),'LineWidth',3,'Color',[0 0 1]);

% Create multiple lines using matrix input to plot
plot3 = plot(X3,YMatrix3,'LineWidth',3);
set(plot3(1),'Color',[0 0.498039215803146 0]);
set(plot3(2),'Color',[0 0 0]);

% Create xlabel
xlabel('Time(s)','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('Angle(Degree)','FontWeight','bold','FontSize',16);

