#!/bin/bash

usize=(    [1]=0.5 [2]=0.5  [3]=0.5  [4]=0.5  [6]=0.5  [8]=0.5  [9]=0.5  [10]=0.5)
esize=(    [1]=2   [2]=2    [3]=2    [4]=2    [6]=3    [8]=1.5  [9]=2.2  [10]=2.2)
pagesteps=([1]=2   [2]=2    [3]=2    [4]=2    [6]=4    [8]=10   [9]=10   [10]=6  )

THESIS_DIR=~/research/ms
TABLES_DIR=$THESIS_DIR/tables
FIGS_DIR=$THESIS_DIR/tablefigs
if ezmake; then
	rm -rf $TABLES_DIR
	mkdir $TABLES_DIR

	rm -rf $FIGS_DIR
	mkdir $FIGS_DIR

	for p in 1 6 8 9 10; do
		rm -rf prob$p
		echo ./loc prob$p.in --usize ${usize[$p]} --etasize ${esize[$p]} --dump prob$p 
		./loc prob$p.in --usize ${usize[$p]} --etasize ${esize[$p]} --pagesteps ${pagesteps[$p]} --dump prob$p 
		# cd prob$p
		# texmake
		# gv wrapper.pdf &
		# cd ..
		cp -v prob$p/table.tex $TABLES_DIR/prob$p.tex
		cp -v prob$p/tablefigs/*.fig $FIGS_DIR
	done
fi

